version: '3.8'

networks:
  shokocapstone:
    external: false

services:
  eureka:
    container_name: eureka
    image: steeltoeoss/eureka-server:latest
    networks:
      - shokocapstone
    ports:
      - '8761:8761'
    restart: always

  gateway:
    container_name: gateway
    image: ssilverman23/capstone:latest
    networks:
      - shokocapstone
    ports:
      - "8888:8888"
    depends_on:
      - eureka

  file-cleanup:
    build:
      context: ./BackEnd/Service1
      dockerfile: dockerfile
    image: file-cleanup
    networks:
      - shokocapstone
    # ports:
      # - "8080:8080"
    deploy:
        replicas : 3
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

  main-learning:
    build:
      context: ./BackEnd/Service2
      dockerfile: dockerfile
    image: main-learning
    networks:
      - shokocapstone
    # ports:
    #   - "8081:8081"
    deploy:
        replicas : 3
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

  use-model:
    build:
      context: ./BackEnd/Service3
      dockerfile: dockerfile
    image: use-model
    networks:
      - shokocapstone
    # ports:
    #   - "8082:8082"
    deploy:
        replicas : 3
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

