FROM python:latest

ADD fileIn.py .

RUN python -m pip cache purge
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# EXPOSE 8080 8080

CMD [ "python", "./fileIn.py", "flask"]