FROM python:latest

ENV DB_USER='ShokoCapstone'
ENV DB_PASS='U5bjze5RVZsHiLn5'

ADD inputData.py .

RUN python -m pip cache purge
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# EXPOSE 8082 8082

CMD [ "python", "./inputData.py", "flask"]