FROM python:latest

ENV DB_USER='ShokoCapstone'
ENV DB_PASS='U5bjze5RVZsHiLn5'

ADD mainLearning.py .

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

EXPOSE 8081 8081

CMD [ "python", "./mainLearning.py", "flask"]