FROM python:latest

ENV DB_USER='ShokoCapstone'
ENV DB_PASS='U5bjze5RVZsHiLn5'

ADD mainLearning.py .

RUN python -m pip cache purge
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

RUN apt-get update -y
RUN apt-get install -y graphviz
# RUN apt install graphviz

# EXPOSE 8081 8081

# ENTRYPOINT [ "/bin/bash", "./installProg.sh" ]
CMD [ "python", "./mainLearning.py", "flask"]